# Action Requires
# 1. Setup the AZURE_CREDENTIALS secrets in your GitHub Repository
# 2. Replace PLEASE_REPLACE_THIS_WITH_YOUR_FUNCTION_APP_NAME with your Azure function app name
# 3. Add this yaml file to your project's .github/workflows/
# 4. Push your local project to your GitHub Repository

name: E2E tests on Azure

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master

      - name: "Test Azure CLI login with service principal"
        uses: azure/actions/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        env:
          SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      
      - run: |
          az account list
          echo "Let's get an access token"
          az account get-access-token -s b92fc3fc-199c-45c2-98ea-23f2898832b7 --query accessToken -o tsv | cut -b 1-100
          echo "Let's access a queue"
          az storage queue exists -n inqueue --account-name yokawasaactionsstor --subscription b92fc3fc-199c-45c2-98ea-23f2898832b7
      - name: "Setup Python 3.6"
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: "Run pip"
        shell: bash
        run: |
          # If your function app project is not located in your repository's root
          # Please change your directory for pip in pushd
          pushd v2functions
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/python3.6/site-packages"
          popd

      - name: "Drop local.settings.json to function app directory"
        env:
          LOCAL_SETTINGS_JSON: ${{ secrets.LOCAL_SETTINGS_JSON }}
        shell: bash
        run: |
          echo $LOCAL_SETTINGS_JSON > v2functions/local.settings.json
          ls -l v2functions/local.settings.json

      - run: |
          pip install azure-cli

      - name: "Create storage queues"
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          for name in 'itemsqueue' 'inqueue' 'outqueue'
          do
            az storage queue create -n $name
          done

      - name: 'Publish Function App to Azure'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ secrets.FUNCTION_APP_NAME }}
          # If your function app project is not located in your repository's root
          # Please consider prefixing the project path in this package parameter
          package: 'v2functions'
          # If you want to use publish profile credentials instead of Azure Service Principal
          # Please uncomment the following line
          publish-profile: ${{ secrets.SCM_CREDENTIALS }}
        
      - run: |
          ls -l

      - name: "Put message into storage queue"
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        shell: bash
        run: |
          az storage message put -q itemsqueue --content 'Hello from action' -o json

      # - name: 'use the published functionapp url in upcoming steps'
      #   run: |
      #   echo "${{ steps.fa.outputs.app-url }}"
